site_url: https://timdavidlee.github.io/fastai2022p2/
site_name: Lecture Notes for Intermediate deep learning
docs_dir: lecture_notes
theme:
    name: material
    palette:
        primary: blue grey
    features:
      - navigation.sections
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
- Home: index.md
- Lesson 9:
  - Pre Lesson: lesson-09/A1-pre-lesson.md
  - Stable Diffusion: lesson-09/A2-stable-diffusion-fun.md
  - Fine Tuning Stable Diffusion: lesson-09/A3-fine-tuning.md
  - Under the Hood: lesson-09/B1-under-the-hood.md
- Lesson 10:
  - Intro: lesson-10/A1-Intro.md
  - Under the hood of Pipeline: lesson-10/A2-pipeline-under-the-hood.md
  - Lists, Matrices and More: lesson-10/A3-lists-matrices-and-more.md
  - More Matrix Operations: lesson-10/A4-matrices.md
  - How Random Numbers are amde: lesson-10/A5-random_numbers.md
- Lesson 11:
  - DiffEdit Paper: lesson-11/A1-diffedit-paper.md
  - Matrix Operations: lesson-11/A2-matrix_operations.md
  - Elementwise Operations: lesson-11/A3-elementwise-ops.md
  - Broadcasting: lesson-11/A4-broadcasting.md
  - More Broadcasting: lesson-11/A5-more-broadcasting.md
  - Matrix Multiplication Broadcasting: lesson-11/A6-matmul-broadcasting.md
- Lesson 12:
  - Intro: lesson-12/A1-intro.md
  - Matmul: lesson-12/A2-matmul.md
  - Implement Clustering with Matrices: lesson-12/A3-mean-shift.md
  - Intro to calculus: lesson-12/A4-calculus.md
- Lesson 13:
  - Intro: lesson-13/A1-intro.md
  - Layers and Modules: lesson-13/A2-refactor.md
  - First training loop: lesson-13/A3-mini-batch-training.md